version: "3.1"

services:
  mongo:
    image: mongo
    networks:
      - taist-networks
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      TZ: "Asia/Bangkok"

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - taist-networks
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
      TZ: "Asia/Bangkok"

  mosq:
    image: eclipse-mosquitto
    container_name: mosquitto_db
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config  # Mount config file
      - ./mosquitto/data:/mosquitto/data  # Data storage
      - ./mosquitto/log:/mosquitto/log  # Log storage
    ports:
      - "1883:1883"  # MQTT Port
    networks:
      - taist-networks

  python:
    build: .
    container_name: database_python
    command: ["python", "app.py"]
    volumes:
      - .:/python-docker  # Maps the current directory to /app inside the container
    ports:
      - "80:8080"
    depends_on:
      - mongo  # Ensure Mosquitto starts before Python app
    networks:
      - taist-networks
    environment:
      DB_ADDRESS: mongodb://root:example@mongo:27017/
      TZ: "Asia/Bangkok"

networks:
  taist-networks:
    driver: bridge
